"""empty message

Revision ID: 4b08200f843c
Revises: 75973210b4ea
Create Date: 2023-04-27 06:29:45.429739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b08200f843c'
down_revision = '75973210b4ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.alter_column('id_kategori',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.alter_column('id_user',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('id_pembayaran',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id_level',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id_level',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)

    with op.batch_alter_table('transaksi', schema=None) as batch_op:
        batch_op.alter_column('id_pembayaran',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
        batch_op.alter_column('id_user',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)

    with op.batch_alter_table('barang', schema=None) as batch_op:
        batch_op.alter_column('id_kategori',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)

    # ### end Alembic commands ###
