"""empty message

Revision ID: 71095a4a033f
Revises: 4b08200f843c
Create Date: 2023-04-27 06:56:44.295118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71095a4a033f'
down_revision = '4b08200f843c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_transaksi', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detail_transaksi', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
