"""empty message

Revision ID: f64e73f3b292
Revises: 
Create Date: 2023-04-27 05:45:36.307063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f64e73f3b292'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kategori',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('level',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pembayaran',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pembayaran', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('barang',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_kategori', sa.BigInteger(), nullable=True),
    sa.Column('kode', sa.BigInteger(), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('harga', sa.BigInteger(), nullable=False),
    sa.Column('stok', sa.BigInteger(), nullable=False),
    sa.Column('penjual', sa.String(length=50), nullable=False),
    sa.Column('lokasi', sa.String(length=50), nullable=False),
    sa.Column('deskripsi', sa.String(length=250), nullable=False),
    sa.Column('terjual', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.BigInteger(), nullable=False),
    sa.Column('rating_5', sa.BigInteger(), nullable=False),
    sa.Column('rating_4', sa.BigInteger(), nullable=False),
    sa.Column('rating_3', sa.BigInteger(), nullable=False),
    sa.Column('rating_2', sa.BigInteger(), nullable=False),
    sa.Column('rating_1', sa.BigInteger(), nullable=False),
    sa.Column('rekomendasi', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id_kategori'], ['kategori.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('id_level', sa.BigInteger(), nullable=True),
    sa.Column('alamat', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('no_telp', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_level'], ['level.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('transaksi',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.BigInteger(), nullable=True),
    sa.Column('id_pembayaran', sa.BigInteger(), nullable=True),
    sa.Column('total_price', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_pembayaran'], ['pembayaran.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail_transaksi',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_transaksi', sa.BigInteger(), nullable=False),
    sa.Column('id_barang', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_barang'], ['barang.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_transaksi'], ['transaksi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detail_transaksi')
    op.drop_table('transaksi')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('barang')
    op.drop_table('pembayaran')
    op.drop_table('level')
    op.drop_table('kategori')
    # ### end Alembic commands ###
